const PACKAGE_DIRECTORY_NAME_PREFIX = 'tkeel-console-';
const PLUGIN_PACKAGE_DIRECTORY_NAME_PREFIX = `${PACKAGE_DIRECTORY_NAME_PREFIX}plugin-`;

const PORTAL_PACKAGE_SIMPLE_NAME = 'portal';
const SHARED_PACKAGE_SIMPLE_NAMES = [
  'business-components',
  'components',
  'hooks',
  'icons',
  'themes',
  'types',
  'utils',
];

const COMMON_PACKAGE_SIMPLE_NAMES = [
  PORTAL_PACKAGE_SIMPLE_NAME,
  ...SHARED_PACKAGE_SIMPLE_NAMES,
];

const EXCLUDE_PACKAGE_NAMES = ['types-tkeel-console'];

module.exports = {
  PACKAGE_DIRECTORY_NAME_PREFIX,
  PLUGIN_PACKAGE_DIRECTORY_NAME_PREFIX,
  PORTAL_PACKAGE_SIMPLE_NAME,
  SHARED_PACKAGE_SIMPLE_NAMES,
  COMMON_PACKAGE_SIMPLE_NAMES,
  EXCLUDE_PACKAGE_NAMES,
};
