const PACKAGE_DIRECTORY_NAME_PREFIX = 'tkeel-console-';
const PLUGIN_PACKAGE_DIRECTORY_NAME_PREFIX = `${PACKAGE_DIRECTORY_NAME_PREFIX}plugin-`;

const CORE_PACKAGE_SIMPLE_NAME = 'core';
const SHARED_PACKAGE_SIMPLE_NAMES = ['components', 'hooks', 'utils'];

const COMMON_PACKAGE_SIMPLE_NAMES = [
  CORE_PACKAGE_SIMPLE_NAME,
  ...SHARED_PACKAGE_SIMPLE_NAMES,
];

module.exports = {
  PACKAGE_DIRECTORY_NAME_PREFIX,
  PLUGIN_PACKAGE_DIRECTORY_NAME_PREFIX,
  CORE_PACKAGE_SIMPLE_NAME,
  SHARED_PACKAGE_SIMPLE_NAMES,
  COMMON_PACKAGE_SIMPLE_NAMES,
};
