apiVersion: v2
name: console-plugin-admin-plugins
description: console of plugin manager
type: application
version: 0.4.0-alpha.2
appVersion: 0.3.0
annotations:
  tkeel.io/enable: 'true'
  tkeel.io/deployment-name: console-plugin-admin-plugins
  tkeel.io/plugin-port: '80'
  tkeel.io/tag: manager
  tkeel.io/version: v0.4.0
maintainers:
  - email: caoyue@yunify.com
    name: caoyue
