apiVersion: v1
kind: Service
metadata:
  name: {{ include "console-plugin-admin-service-monitoring.name" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: {{ include "console-plugin-admin-service-monitoring.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
  type: ClusterIP
