FROM node:16-slim as BUILDER

RUN apt clean \
  && apt update \
  && yarn set version stable \
  && npm install -g cross-env webpack webpack-cli

ARG PACKAGE_NAME
ENV NODE_OPTIONS=--max_old_space_size=2048

WORKDIR /app
COPY ./ ./
RUN yarn && yarn workspace ${PACKAGE_NAME} build
