FROM node:16-slim as BUILDER

RUN apt clean \
  && apt update \
  && yarn set version stable \
  && npm config set registry https://registry.npm.taobao.org \
  && npm install -g cross-env webpack webpack-cli

ARG PACKAGE_NAME
ENV NODE_OPTIONS=--max_old_space_size=4096

WORKDIR /app
COPY ./ ./
RUN yarn \
  && yarn workspace ${PACKAGE_NAME} build
