apiVersion: v2
name: console-plugin-tenant-users
description: tenant and user console
type: application
version: 0.4.0-alpha.3
appVersion: 0.3.0
annotations:
  tkeel.io/enable: 'true'
  tkeel.io/deployment-name: console-plugin-tenant-users
  tkeel.io/plugin-port: '80'
  tkeel.io/tag: manager
  tkeel.io/version: v0.4.0
maintainers:
  - email: caoyue@yunify.com
    name: caoyue
